title: Josiel Manzonni
email: josiel@example.com
description: Principal Software Engineer specializing in Backend Architecture, Android, Distributed Systems, Cloud, Payments and Technical Leadership.
baseurl: "/bestengineer"
url: "https://josielmanzonni.github.io"
twitter_username: josielmanzonni
github_username: JosielManzonni
markdown: kramdown
exclude:
  - README.md
  - node_modules
